---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

server:
  server_address: "localhost:8080"
  rounds: 100
  num_clients: 15
  min_sample_size: 15
  gpu_memory: 2048
  eval_step: 1
  train_epochs: 1
  batch_size: 64
  learning_rate: 0.001
  dataset_name: "ambient_context"
  seed: 2021
  verbose: 1

client:
  server_address: "localhost:8080"
  num_clients: 15
  gpu_memory: 1024
  dataset_name: "ambient_context"
  seed: 2021
  batch_size: 64
  l_per: 0.2
  u_per: 0.8
  fedstar: "true"
  class_distribute: "false"
  verbose: 1